version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./Ph_o:/Ph_o
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py makemigrations&&
             python3 manage.py migrate&&
             python3 manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORDS=${EMAIL_HOST_PASSWORDS}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - DEFAULT_TO_EMAIL=${DEFAULT_TO_EMAIL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - DB_HOST=db
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    tty: true
    stdin_open: true
